version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # Deploy the broker.
  rabbitmq_server:
    image: rabbitmq
    ports:
      # Expose the port for the worker to add/get tasks
      - 5672:5672
      # OPTIONAL: Expose the GUI port
      - 15672:15672

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    # env_file:
    #   - local.env
    network_mode: host
    command: bash -c 'celery -A api worker --loglevel=INFO'
    volumes:
      - .:/app
    environment:
      rabbitmq_uri: amqp://127.0.0.1:5672
    depends_on: 
      - rabbitmq_server
      # - db
      - backend
      
  beat:
    build:
      context: .
      dockerfile: Dockerfile
    # env_file:
    #   - local.env
    network_mode: host
    command: bash -c 'celery -A api beat --loglevel=INFO'
    volumes:
      - .:/app
    environment:
      rabbitmq_uri: amqp://127.0.0.1:5672
    depends_on: 
      - rabbitmq_server
      - worker
      # - db
      - backend

  backend:
    build: .
    env_file:
      - local.env
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py migrate; python manage.py runserver 0.0.0.0:8000 --noreload'
    links:
      - db:db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "4000:4000"
    depends_on:
      - db
      - rabbitmq_server

